
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IN = 11;
  public static final int STRING_LITERAL = 12;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int LBRAC = 5;
  public static final int EQ = 7;
  public static final int IF = 9;
  public static final int ELSE = 10;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 13;
  public static final int LPAREN = 3;
  public static final int RBRAC = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "EQ",
  "COMMA",
  "IF",
  "ELSE",
  "IN",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

